export default {
    0: {categoria: 'lácteos', cantidad: 2, precio: 3500, producto: 'Leche colanta'},
    1: {categoria: 'lácteos', cantidad: 25, precio: 4500, producto: 'Alpinito x15ml'},
    2: {categoria: 'lácteos', cantidad: 52, precio: 35200, producto: 'Quesillo x1000gr'},
    3: {categoria: 'lácteos', cantidad: 100, precio: 18000, producto: 'Quesillo x500gr'},
    4: {categoria: 'lácteos', cantidad: 10, precio: 4500, producto: 'Yogurt griego'},
    5: {categoria: 'carnes', cantidad: 145, precio: 32800, producto: 'Libra carne res'},
    6: {categoria: 'carnes', cantidad: 10, precio: 35200, producto: 'Libra carne cerdo'},
    7: {categoria: 'carnes', cantidad: 25, precio: 18240, producto: 'Libra pollo'},
    8: {categoria: 'carnes', cantidad: 289, precio: 9900, producto: 'Libra bagre'},
    9: {categoria: 'enlatados', cantidad: 758, precio: 9900, producto: 'Arveja enlatada'},
    10: {categoria: 'enlatados', cantidad: 2789, precio: 12360, producto: 'Frijoles picantes'},
    11: {categoria: 'enlatados', cantidad: 36, precio: 8900, producto: 'Maicitos x500gr'},
    12: {categoria: 'enlatados', cantidad: 2, precio: 9900, producto: 'Libra papa'},
    13: {categoria: 'verduras', cantidad: 100, precio: 5600, producto: 'Libra Zanahoria'},
    14: {categoria: 'verduras', cantidad: 85, precio: 12500, producto: 'Libra tomate'},
    15: {categoria: 'verduras', cantidad: 100, precio: 8450, producto: 'Libra cebolla'},
    16: {categoria: 'verduras', cantidad: 52, precio: 3200, producto: 'Libra perejil'},
    17: {categoria: 'verduras', cantidad: 52, precio: 4500, producto: 'Libra habichuela'},
}